/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    BottomPanel: typeof import('./components/layout/BottomPanel.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    CytoscapeGraph: typeof import('./components/CytoscapeGraph.vue')['default']
    MainContent: typeof import('./components/layout/MainContent.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    ResizablePanel: typeof import('./components/layout/ResizablePanel.vue')['default']
    ResizableSplit: typeof import('./components/layout/ResizableSplit.vue')['default']
    ResourceSection: typeof import('./components/layout/ResourceSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/layout/SideBar.vue')['default']
    TopBar: typeof import('./components/layout/TopBar.vue')['default']
    VisualEditor: typeof import('./components/VisualEditor.vue')['default']
  }
}
